/*
 * This source file was generated by the Gradle 'init' task
 */
package lab;

import java.util.List;

import lab.models.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Working Directory = " + System.getProperty("user.dir"));
        List<Customer> customers = Customer.createObjectsFromCSV("src/main/java/lab/models/input.txt");

        System.out.println(customers);
    }
}
