/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

//import org.gretty.GrettyExtension


plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("war")
    id("org.gretty") version "4.1.10"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Application dependencies
    implementation(libs.guava)
    implementation ("org.hibernate.validator:hibernate-validator:8.0.1.Final")
          
          // Expression Language (важливо!)
    implementation ("org.glassfish.expressly:expressly:6.0.0")
    implementation("org.slf4j:slf4j-api:2.0.13")
    implementation("org.slf4j:slf4j-simple:2.0.13")
    implementation("ch.qos.logback:logback-classic:1.4.14")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.18.0")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.18.0")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.20.0")

    
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
//
gretty {
    httpPort = 8080
    contextPath = "/api"
    servletContainer = "tomcat10"   // або "jetty11" тощо
}


application {
    // Define the main class for the application.
    mainClass = "lab.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.war {
    archiveFileName.set("order-api.war")
}

repositories {
    mavenCentral()
}
